### ISSUE TITLE
ECR images / Dockerfile in lieu of image

### ISSUE THREAD

**Issue by vishalovercome** [okteto/remote-kubernetes#157]
This project is great and I want to use your VSCode extension to do remote development. I currently have a Dockerfile that's used to build a devcontainer with vscode server running inside it. Your VSCode extension allows users to provide an image name and I wanted to know whether:

1. I can provide my Dockerfile instead of image. Can you share an example?
2. If I can't use my Dockerfile, then I suppose I could push an image to AWS ECR but I'm not sure if your offering allows pulling images that aren't in Docker Hub

How can someone in my position get going with your project? It will be a game changer but I can only use my own Dockerfile.

**Comment by vishalovercome** [comment]
I suppose there's a way to pull from ECR - https://okteto.com/docs/reference/faqs/#how-to-use-private-images. However, this would be a bit too rigid as part and parcel of development would be experimenting with the dockefile itself and being able to spin up containers after tweaking. Any plan to integrate it with VSCode devcontainer so that we can simply "clone repository into a container volume" wherein the container itself runs in kubernetes?

**Comment by rberrelleza** [comment]
@vishalovercome these are great comments, thanks!

1. Today, the extension assumes the docker image is already available. If you have a Dockerfile, you could pass the `--build` parameter to the up command (you can do this in the settings) to build it on the fly. 
2. Yes, you can pull images from anywhere, as long as your cluster has the credentials. https://okteto.com/docs/reference/faqs/#how-to-use-private-images has instructions for any cluster. If you're running in Okteto Cloud, I'd recommend you check out Okteto Registry, since it's fully integrated with your account, and doesn't require setting extra credentials. 

I'm curious why do you have an image with vscode server running on it? The remote-ssh extension (which okteto leverages) will install that automatically for you.

**Comment by rberrelleza** [comment]
> I suppose there's a way to pull from ECR - https://okteto.com/docs/reference/faqs/#how-to-use-private-images. However, this would be a bit too rigid as part and parcel of development would be experimenting with the dockefile itself and being able to spin up containers after tweaking. Any plan to integrate it with VSCode devcontainer so that we can simply "clone repository into a container volume" wherein the container itself runs in kubernetes?

We don't have any short term plans for this mode, but this is an interesting approach. Not sure if the VSCode extensions can access that functionality, but we'll research it.

**Comment by rberrelleza** [comment]
>  I can provide my Dockerfile instead of image. Can you share an example?

This is now possible if you are using Okteto v2.  Okteto will automatically build the Dockerfile using either a local docker install, or okteto's build service (if you are logged into okteto cloud or an okteto self-hosted instance).  https://github.com/okteto/movies is a good example of it. 

Try it out and let us know?
